In [4]:
import pandas as pd

In [16]:
pd.set_option('display.max_columns', None)

In [17]:
data1_path = "dataset.csv"
data2_path = "dataset2.csv"

In [18]:
df = pd.read_csv(data1_path)
df.head()

,opportunity_id,content_id,vol_requests,event_time,title,hits,summary,is_priority,category_id,category_desc,amsl,amsl_unit,org_title,org_content_id,addresses_count,locality,region,Postcode,primary_loc,display_url,recurrence_type,hours,created_date,last_modified_date,start_date_date,end_date_date,status,Borough,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA,Zip Codes,Community Districts,Borough Boundaries,City Council Districts,Police Precincts
0,5017,37156,5,0,Cents Ability Classroom Set-up,0,Help us set up a new training classroom to tea...,NaN,1.0,Strengthening Communities,NaN,NaN,"Cents Ability, Inc.",37154,1,"{'latitude': '40.72664935898081', 'longitude':...",NY,10009.0,NaN,/opportunities/5017,onetime,0,January 19 2011,January 26 2011,January 22 2011,January 22 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11729.0,70.0,4.0,50.0,5.0
1,5141,38165,5,0,Mentor Homeless Youth,314,Mentor homeless children between the ages of 2...,NaN,3.0,Education,NaN,NaN,Metropolitan Council on Jewish Poverty,974,1,"{'latitude': '40.71075497033968', 'longitude':...",NY,11432.0,NaN,/opportunities/5141,ongoing,0,February 28 2011,September 19 2011,September 19 2011,December 31 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24340.0,25.0,3.0,24.0,65.0
2,5288,39274,5,0,"Journalism, Copywriting, Creative Writing Oppo...",551,"Are you interested in journalism, research, wr...",NaN,NaN,NaN,NaN,NaN,Hearts and Minds,39195,1,"{'latitude': '40.79937645675807', 'longitude':...",NY,10025.0,NaN,/opportunities/5288,ongoing,0,April 14 2011,April 18 2011,April 14 2011,April 13 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12422.0,20.0,4.0,23.0,15.0
3,5475,41369,10,0,Volunteers Needed for Senior Lunch Program!,54,"In celebration of Father's Day, we invite fath...",y,2.0,Helping Neighbors in Need,NaN,NaN,Metropolitan Council on Jewish Poverty,974,1,NaN,NY,10016.0,NaN,/opportunities/5475,onetime,0,June 16 2011,June 17 2011,June 19 2011,June 19 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5045,37372,40,0,Special Events Assistant,577,The Police Athletic League of New York City se...,NaN,1.0,Strengthening Communities,NaN,NaN,Police Athletic League Of New York,3067,1,"{'latitude': '40.734434119371144', 'longitude'...",NY,10003.0,NaN,/opportunities/5045,ongoing,0,January 26 2011,January 26 2011,January 26 2011,January 10 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11724.0,57.0,4.0,50.0,3.0

In [19]:
df2 = pd.read_csv(data2_path)
df2.head()

,Requirements,opportunity_id,content_id:,Summary,Category Description,Title,display_url,Recurrence_type,Street Address,2nd Address,City,State,Postcode,Country,Website,Borough,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,<p>Volunteers must be 18 years of age or older...,Adult Education and Job Readiness Projects wit...,<p>Planning for a better future starts by beli...,Planning for a better future starts by believi...,NaN,New York Cares,/opportunities/69,ongoing,"65 Broadway, 19th Floor",NaN,New York,NY,10006,US,http://www.newyorkcares.org,MANHATTAN,40.707113,-74.012234,101.0,1.0,13.0,1000809.0,1.000210e+09,Battery Park City-Lower Manhattan
1,<p>There will be one day of required volunteer...,Arts and Crafts Volunteers,<p>Arts and Crafts volunteers are needed to as...,Arts and Crafts volunteers are needed to assis...,Communities and Neighbors,Project HAPPY,/opportunities/103,ongoing,425 East 25th Street,NaN,Manhattan,NY,10010,US,http://www.project-happy.org,MANHATTAN,40.737878,-73.976880,106.0,4.0,62.0,1069579.0,1.009620e+09,Murray Hill-Kips Bay
2,<p>Previous experience working in an administr...,After-School Program Coordinator,<p>• Provides oral and written reports to the ...,Assist Executive Director in managing after-sc...,Education,Rise Up & Walk Youth Outreach Center Inc,/opportunities/163,ongoing,432 Monroe Street,NaN,Brooklyn,NY,11221,US,http://www.riseupnwalk.org,BROOKLYN,40.686592,-73.940747,303.0,36.0,277.0,3051540.0,3.018210e+09,Stuyvesant Heights
3,<p>Volunteers must be 18 years of age or older...,Adults and Children with Special Needs Project...,<p>New York Cares offers many programs serving...,New York Cares offers many programs serving ad...,NaN,New York Cares,/opportunities/206,ongoing,"65 Broadway, 19th Floor",NaN,New York,NY,10001,US,http://www.newyorkcares.org,MANHATTAN,40.707113,-74.012234,101.0,1.0,13.0,1000809.0,1.000210e+09,Battery Park City-Lower Manhattan
4,<p>Volunteers must be 18 years of age or older...,Animal Care Projects with New York Cares,<p>Socialize with rescued animals and help the...,Socialize with rescued animals and help them g...,NaN,New York Cares,/opportunities/207,ongoing,"65 Broadway, 19th Floor",NaN,New York,NY,10001,US,http://www.newyorkcares.org,MANHATTAN,40.707113,-74.012234,101.0,1.0,13.0,1000809.0,1.000210e+09,Battery Park City-Lower Manhattan

Combine the important columns of datasets:

In [59]:
sums = pd.concat([df["summary"], df2["Summary"]], ignore_index=True)
titles = pd.concat([df["title"], df2["opportunity_id"]], ignore_index=True)
categories = pd.concat([df["category_desc"], df2["Category Description"]], ignore_index=True)

In [60]:
joined = pd.DataFrame()
joined["sum"] = sums
joined["title"] = titles
joined["category"] = categories

In [61]:
joined.to_csv

,sum,title,category
0,Help us set up a new training classroom to tea...,Cents Ability Classroom Set-up,Strengthening Communities
1,Mentor homeless children between the ages of 2...,Mentor Homeless Youth,Education
2,"Are you interested in journalism, research, wr...","Journalism, Copywriting, Creative Writing Oppo...",NaN
3,"In celebration of Father's Day, we invite fath...",Volunteers Needed for Senior Lunch Program!,Helping Neighbors in Need
4,The Police Athletic League of New York City se...,Special Events Assistant,Strengthening Communities